services:
  frontend:
    build:
      context: ./my-react-editor
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./my-react-editor/.env.local
    depends_on:
      - backend

  backend:
    build:
      context: ./my-react-editor/Backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./my-react-editor/Backend/.env
